# config/cable.yml

development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: common_cosmetics_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: common_cosmetics_production
